### ISSUE TITLE
Create the media service

### ISSUE THREAD

**Issue by omcneil** [openpracticelibrary/opl-media-service#2]
As an engineer, I need to abstract content creation from the Strapi based service, so that I can upload images to the appropriate location, and so that I can provide a content verification and versioning service.

ACCEPTANCE CRITERIA (as persona):
**Given** I need to create content for OPL,
**When** I upload content through the OPL UI,
**Then** I expect the content to be uploaded, 
**And** I expect that the content is sent for approval.

NOTES:
- Need Graph QL, Express, its own database and a way to filter images from the POST and put them in S3 and return a URL
- Needs to index new content and updated content to allow for versioning 

BLOCKERS:
None

**Comment by shaheinm** [comment]
Media service created and works as a standalone.  Need to make modifications to the api gateway to allow file uploads to pass through to the media service when working through Apollo Federation.
