### ISSUE TITLE
SPIKE: Image hosting, CDNs, and processing, oh my!

### ISSUE THREAD

**Issue by shaheinm** [openpracticelibrary/opl-media-service#4]
The development team has been having a conversation about our approach to image processing, compression, storage and retrieval, and this Spike is meant to capture that conversation.

**Comment by shaheinm** [comment]
From what @cognizen had been talking about, I'm leaning towards the idea that we continue with the way I had originally thought of it, with the only question now being where to store it (and doing it ourselves wouldn't be out of the question):

1. Object storage makes the most sense.  The designs for the application would need at least an image with a thumbnail size and a media gallery "primary" size.  We would likely also want to store the image in its original size.  An object (with the graphql service in front of it) would be the simplest way to store those related images next to each other.

2. As Philip mentioned, GraphicsMagick is tried and true, and the [npm package](https://www.npmjs.com/package/gm) is simple and well documented.

3. We keep it all open source, with no subscriptions to manage on our side, and still don't add much at all in the way of code bases to manage.

**Comment by shaheinm** [comment]
Went with the Options label because there is still an option to continue development the way we have been.

With that in mind, here is what we were thinking going in, for those who may not be aware:
1. The image is passed to the API Gateway with a graphql mutation
2. The API gateway sends the mutation to the media service.
3. The media service then resizes the image a couple of ways, and compresses it, then sends the images to S3.  You'd have sub directories in the s3 bucket like `original`, `thumbnail`, `preview`, etc

If we want to keep it open source and still use something like S3 (wonderful object storage API that it is), something like [minio](https://min.io/) could be an option.

**Comment by shaheinm** [comment]
[This](https://rook.io/) would be a very interesting solution (to the storage question), if we can have someone with cluster admin privileges install the operator. Open source, built for Kubernetes and CNCF.

**Comment by shaheinm** [comment]
For what it's worth, Apollo recommends splitting the file processing and upload to yet another service behind the GraphQL media service.  That way, GraphQL would just be the query service (which makes sense from a separation of concerns perspective, if a bit extreme for our purpose *right now*) 

https://www.apollographql.com/blog/apollo-server-file-upload-best-practices-1e7f24cdc050

Given that we are storing the links to the files in the GraphQL-based content API, we don't actually need the media service to be a GraphQL enabled service. The only drawback is that there'd be a REST service to set up and interact with on the front-end.

Another option would be to generated pre-signed URLs with the media-service, return that when the file upload mutation comes through, and the front end can send the file to the pre-signed URL in the callback... The drawback being we don't process or compress any images and therefore cannot create thumbnails and such.

**Comment by shaheinm** [comment]
@Venus-Izadi @cognizen @jameshbarton @piyushsn 

- EPIPHANY - 

Let's store the files in Git, and serve them with GitHub Pages!!!!

**Comment by philipdouble** [comment]
Test speeds looked good - sres will smile - free... Sounds like a winner to me...
